# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/comms_ariel/proto/comms_ariel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/comms_ariel/proto/comms_ariel.proto',
  package='comms_ariel',
  syntax='proto3',
  serialized_pb=_b('\n\'src/comms_ariel/proto/comms_ariel.proto\x12\x0b\x63omms_ariel\".\n\x0f\x43ommonTelemetry\x12\x0f\n\x07time_us\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\r\"\xd8\x01\n\x0cUSVTelemetry\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x13\n\x0borientation\x18\x04 \x03(\x01\x12\x12\n\nvelocity_n\x18\x05 \x01(\x02\x12\x12\n\nvelocity_w\x18\x06 \x01(\x02\x12/\n\x05state\x18\x08 \x01(\x0e\x32 .comms_ariel.USVTelemetry.States\"5\n\x06States\x12\x0b\n\x07TRANSIT\x10\x00\x12\x0e\n\nTAKEOFF_OK\x10\x01\x12\x0e\n\nLANDING_OK\x10\x02\"\xb4\x01\n\x0e\x44roneTelemetry\x12\x19\n\x11loaded_mission_id\x18\x01 \x01(\x04\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x02\x12\x31\n\x05state\x18\x08 \x01(\x0e\x32\".comms_ariel.DroneTelemetry.States\"\x1d\n\x06States\x12\x13\n\x0fWAITING_LANDING\x10\x00\"c\n\x07Mission\x12\x12\n\nmission_id\x18\x01 \x01(\x04\x12\x11\n\twaypoints\x18\x02 \x03(\x01\x12\x1a\n\x12usv_reference_time\x18\x03 \x01(\x04\x12\x15\n\rusv_waypoints\x18\x04 \x03(\x01\"\x96\x01\n\x11USVToDroneMessage\x12,\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x1c.comms_ariel.CommonTelemetry\x12,\n\ttelemetry\x18\x02 \x01(\x0b\x32\x19.comms_ariel.USVTelemetry\x12%\n\x07mission\x18\x03 \x01(\x0b\x32\x14.comms_ariel.Mission\"q\n\x11\x44roneToUSVMessage\x12,\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x1c.comms_ariel.CommonTelemetry\x12.\n\ttelemetry\x18\x02 \x01(\x0b\x32\x1b.comms_ariel.DroneTelemetryb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USVTELEMETRY_STATES = _descriptor.EnumDescriptor(
  name='States',
  full_name='comms_ariel.USVTelemetry.States',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAKEOFF_OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LANDING_OK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=268,
  serialized_end=321,
)
_sym_db.RegisterEnumDescriptor(_USVTELEMETRY_STATES)

_DRONETELEMETRY_STATES = _descriptor.EnumDescriptor(
  name='States',
  full_name='comms_ariel.DroneTelemetry.States',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WAITING_LANDING', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=475,
  serialized_end=504,
)
_sym_db.RegisterEnumDescriptor(_DRONETELEMETRY_STATES)


_COMMONTELEMETRY = _descriptor.Descriptor(
  name='CommonTelemetry',
  full_name='comms_ariel.CommonTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_us', full_name='comms_ariel.CommonTelemetry.time_us', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='comms_ariel.CommonTelemetry.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=102,
)


_USVTELEMETRY = _descriptor.Descriptor(
  name='USVTelemetry',
  full_name='comms_ariel.USVTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='comms_ariel.USVTelemetry.latitude', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='comms_ariel.USVTelemetry.longitude', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='comms_ariel.USVTelemetry.orientation', index=2,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_n', full_name='comms_ariel.USVTelemetry.velocity_n', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_w', full_name='comms_ariel.USVTelemetry.velocity_w', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='comms_ariel.USVTelemetry.state', index=5,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USVTELEMETRY_STATES,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=321,
)


_DRONETELEMETRY = _descriptor.Descriptor(
  name='DroneTelemetry',
  full_name='comms_ariel.DroneTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loaded_mission_id', full_name='comms_ariel.DroneTelemetry.loaded_mission_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='comms_ariel.DroneTelemetry.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='comms_ariel.DroneTelemetry.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='comms_ariel.DroneTelemetry.altitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='comms_ariel.DroneTelemetry.state', index=4,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRONETELEMETRY_STATES,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=504,
)


_MISSION = _descriptor.Descriptor(
  name='Mission',
  full_name='comms_ariel.Mission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mission_id', full_name='comms_ariel.Mission.mission_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='comms_ariel.Mission.waypoints', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usv_reference_time', full_name='comms_ariel.Mission.usv_reference_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usv_waypoints', full_name='comms_ariel.Mission.usv_waypoints', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=605,
)


_USVTODRONEMESSAGE = _descriptor.Descriptor(
  name='USVToDroneMessage',
  full_name='comms_ariel.USVToDroneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='comms_ariel.USVToDroneMessage.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='comms_ariel.USVToDroneMessage.telemetry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mission', full_name='comms_ariel.USVToDroneMessage.mission', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=608,
  serialized_end=758,
)


_DRONETOUSVMESSAGE = _descriptor.Descriptor(
  name='DroneToUSVMessage',
  full_name='comms_ariel.DroneToUSVMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='comms_ariel.DroneToUSVMessage.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='comms_ariel.DroneToUSVMessage.telemetry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=760,
  serialized_end=873,
)

_USVTELEMETRY.fields_by_name['state'].enum_type = _USVTELEMETRY_STATES
_USVTELEMETRY_STATES.containing_type = _USVTELEMETRY
_DRONETELEMETRY.fields_by_name['state'].enum_type = _DRONETELEMETRY_STATES
_DRONETELEMETRY_STATES.containing_type = _DRONETELEMETRY
_USVTODRONEMESSAGE.fields_by_name['common'].message_type = _COMMONTELEMETRY
_USVTODRONEMESSAGE.fields_by_name['telemetry'].message_type = _USVTELEMETRY
_USVTODRONEMESSAGE.fields_by_name['mission'].message_type = _MISSION
_DRONETOUSVMESSAGE.fields_by_name['common'].message_type = _COMMONTELEMETRY
_DRONETOUSVMESSAGE.fields_by_name['telemetry'].message_type = _DRONETELEMETRY
DESCRIPTOR.message_types_by_name['CommonTelemetry'] = _COMMONTELEMETRY
DESCRIPTOR.message_types_by_name['USVTelemetry'] = _USVTELEMETRY
DESCRIPTOR.message_types_by_name['DroneTelemetry'] = _DRONETELEMETRY
DESCRIPTOR.message_types_by_name['Mission'] = _MISSION
DESCRIPTOR.message_types_by_name['USVToDroneMessage'] = _USVTODRONEMESSAGE
DESCRIPTOR.message_types_by_name['DroneToUSVMessage'] = _DRONETOUSVMESSAGE

CommonTelemetry = _reflection.GeneratedProtocolMessageType('CommonTelemetry', (_message.Message,), dict(
  DESCRIPTOR = _COMMONTELEMETRY,
  __module__ = 'src.comms_ariel.proto.comms_ariel_pb2'
  # @@protoc_insertion_point(class_scope:comms_ariel.CommonTelemetry)
  ))
_sym_db.RegisterMessage(CommonTelemetry)

USVTelemetry = _reflection.GeneratedProtocolMessageType('USVTelemetry', (_message.Message,), dict(
  DESCRIPTOR = _USVTELEMETRY,
  __module__ = 'src.comms_ariel.proto.comms_ariel_pb2'
  # @@protoc_insertion_point(class_scope:comms_ariel.USVTelemetry)
  ))
_sym_db.RegisterMessage(USVTelemetry)

DroneTelemetry = _reflection.GeneratedProtocolMessageType('DroneTelemetry', (_message.Message,), dict(
  DESCRIPTOR = _DRONETELEMETRY,
  __module__ = 'src.comms_ariel.proto.comms_ariel_pb2'
  # @@protoc_insertion_point(class_scope:comms_ariel.DroneTelemetry)
  ))
_sym_db.RegisterMessage(DroneTelemetry)

Mission = _reflection.GeneratedProtocolMessageType('Mission', (_message.Message,), dict(
  DESCRIPTOR = _MISSION,
  __module__ = 'src.comms_ariel.proto.comms_ariel_pb2'
  # @@protoc_insertion_point(class_scope:comms_ariel.Mission)
  ))
_sym_db.RegisterMessage(Mission)

USVToDroneMessage = _reflection.GeneratedProtocolMessageType('USVToDroneMessage', (_message.Message,), dict(
  DESCRIPTOR = _USVTODRONEMESSAGE,
  __module__ = 'src.comms_ariel.proto.comms_ariel_pb2'
  # @@protoc_insertion_point(class_scope:comms_ariel.USVToDroneMessage)
  ))
_sym_db.RegisterMessage(USVToDroneMessage)

DroneToUSVMessage = _reflection.GeneratedProtocolMessageType('DroneToUSVMessage', (_message.Message,), dict(
  DESCRIPTOR = _DRONETOUSVMESSAGE,
  __module__ = 'src.comms_ariel.proto.comms_ariel_pb2'
  # @@protoc_insertion_point(class_scope:comms_ariel.DroneToUSVMessage)
  ))
_sym_db.RegisterMessage(DroneToUSVMessage)


# @@protoc_insertion_point(module_scope)
